// <auto-generated />
using CPRG214.Vani.AssetTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG214.Vani.AssetTracker.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    [Migration("20200514210108_CreateAssetTracker")]
    partial class CreateAssetTracker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPRG214.Vani.AssetTracker.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Asset");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetTypeId = 1,
                            Description = "Computers by Dell",
                            Manufacturer = "Computer",
                            Model = "Dell",
                            SNo = "C2DELL",
                            TagNo = "1234"
                        },
                        new
                        {
                            Id = 2,
                            AssetTypeId = 1,
                            Description = "Computers by HP",
                            Manufacturer = "Computer",
                            Model = "HP",
                            SNo = "C1HP",
                            TagNo = "1034"
                        },
                        new
                        {
                            Id = 3,
                            AssetTypeId = 1,
                            Description = "Computers by Acer",
                            Manufacturer = "Computer",
                            Model = "Acer",
                            SNo = "C1ACER",
                            TagNo = "1205"
                        },
                        new
                        {
                            Id = 4,
                            AssetTypeId = 2,
                            Description = "Monitors by Acer",
                            Manufacturer = "Monitor",
                            Model = "Acer",
                            SNo = "M2ACER",
                            TagNo = "5401"
                        },
                        new
                        {
                            Id = 5,
                            AssetTypeId = 2,
                            Description = "Monitors By LG",
                            Manufacturer = "Monitor",
                            Model = "LG",
                            SNo = "M3LG",
                            TagNo = "1204"
                        },
                        new
                        {
                            Id = 6,
                            AssetTypeId = 2,
                            Description = "Monitors By HP",
                            Manufacturer = "Monitor",
                            Model = "HP",
                            SNo = "M1HP",
                            TagNo = "1001"
                        },
                        new
                        {
                            Id = 7,
                            AssetTypeId = 3,
                            Description = "Phones By Avaya",
                            Manufacturer = "Phone",
                            Model = "Avaya",
                            SNo = "P4AVAYA",
                            TagNo = "1308"
                        },
                        new
                        {
                            Id = 8,
                            AssetTypeId = 3,
                            Description = "Phones By Polycom",
                            Manufacturer = "Phone",
                            Model = "Polycom",
                            SNo = "P3PPLY",
                            TagNo = "1400"
                        },
                        new
                        {
                            Id = 9,
                            AssetTypeId = 3,
                            Description = "Phones By Cisco",
                            Manufacturer = "Phone",
                            Model = "Cisco",
                            SNo = "P9CISCO",
                            TagNo = "1604"
                        });
                });

            modelBuilder.Entity("CPRG214.Vani.AssetTracker.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phone"
                        });
                });

            modelBuilder.Entity("CPRG214.Vani.AssetTracker.Domain.Asset", b =>
                {
                    b.HasOne("CPRG214.Vani.AssetTracker.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
